name: GitHub Pages

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache 💵
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-
      - name: Install 📦
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Sassdoc 💄
        run: npm run build:sassdoc -- --dest website/static/sassdoc
      - name: Build Storybook 📚
        run: npm run build:stories -- --output-dir website/static/storybook
      - name: Build docs 📄
        run: npm run build:docs
        env:
          BASE_URL: /design-system/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
